language: ruby
sudo: required
addons:
 chrome: stable

before_install:
 - gem update --system
 - gem install cucumber capybara selenium rspec 'selenium-webdriver'
 - wget http://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip
 - rm chromedriver_linux64.zip
 - sudo mv -f chromedriver /usr/local/bin/
 - sudo chmod +x /usr/local/bin/chromedriver
 - google-chrome-stable --headless --no-sandbox
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start